const actionNames = {
  SET_CART_ADD: "SET_CART_ADD",
  SET_CART_REMOVE: "SET_CART_REMOVE",
  SET_CART_CLEAR: "SET_CART_CLEAR",
  SET_LIKED_ADD: "SET_LIKED_ADD",
  SET_LIKED_REMOVE: "SET_LIKED_REMOVE",
  SET_WALLET_MINUS: "GET_LIKED",
  SET_WALLET_PLUS: "GET_LIKED_NUMBER",
};
export default actionNames;
