const getterNames = {
  GET_CART_TOTAL: "GET_CART_TOTAL",
  GET_CART_WEIGHT: "GET_CART_WEIGHT",
  GET_CART_QUANTITY: "GET_CART_QUANTITY",
  GET_CART_PRODUCTS: "GET_CART_PRODUCTS",
  GET_CART_NUMBER: "GET_CART_NUMBER",
  GET_LIKED: "GET_LIKED",
  GET_LIKED_NUMBER: "GET_LIKED_NUMBER",
  GET_WALLET: "GET_WALLET",
};
export default getterNames;

