const mutationNames = {
  MUTATE_ADD_TO_CART: "MUTATE_ADD_TO_CARD",
  MUTATE_REMOVE_FROM_CART: "MUTATE_REMOVE_FROM_CART",
  MUTATE_CLEAR_CART: "MUTATE_CLEAR_CART",
  MUTATE_ADD_TO_LIKED: "MUTATE_ADD_TO_LIKED",
  MUTATE_REMOVE_FROM_LIKED: "MUTATE_REMOVE_FROM_LIKED",
  MUTATE_WALLET_MINUS: "MUTATE_WALLET_MINUS",
  MUTATE_WALLET_PLUS: "MUTATE_WALLET_PLUS",
};
export default mutationNames;
